"""Initial schema

Revision ID: 49abf5dd75b7
Revises: 
Create Date: 2026-04-29 17:15:49.333733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49abf5dd75b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversion_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_unit', sa.String(), nullable=True),
    sa.Column('to_unit', sa.String(), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversion_factors_from_unit'), 'conversion_factors', ['from_unit'], unique=False)
    op.create_index(op.f('ix_conversion_factors_id'), 'conversion_factors', ['id'], unique=False)
    op.create_index(op.f('ix_conversion_factors_to_unit'), 'conversion_factors', ['to_unit'], unique=False)
    op.create_table('energy_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('unit_default', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_sources_id'), 'energy_sources', ['id'], unique=False)
    op.create_index(op.f('ix_energy_sources_name'), 'energy_sources', ['name'], unique=True)
    op.create_table('isic_sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_isic_sectors_code'), 'isic_sectors', ['code'], unique=True)
    op.create_index(op.f('ix_isic_sectors_id'), 'isic_sectors', ['id'], unique=False)
    op.create_table('energy_fact_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['isic_sectors.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['energy_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_fact_data_id'), 'energy_fact_data', ['id'], unique=False)
    op.create_index(op.f('ix_energy_fact_data_timestamp'), 'energy_fact_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_energy_fact_data_timestamp'), table_name='energy_fact_data')
    op.drop_index(op.f('ix_energy_fact_data_id'), table_name='energy_fact_data')
    op.drop_table('energy_fact_data')
    op.drop_index(op.f('ix_isic_sectors_id'), table_name='isic_sectors')
    op.drop_index(op.f('ix_isic_sectors_code'), table_name='isic_sectors')
    op.drop_table('isic_sectors')
    op.drop_index(op.f('ix_energy_sources_name'), table_name='energy_sources')
    op.drop_index(op.f('ix_energy_sources_id'), table_name='energy_sources')
    op.drop_table('energy_sources')
    op.drop_index(op.f('ix_conversion_factors_to_unit'), table_name='conversion_factors')
    op.drop_index(op.f('ix_conversion_factors_id'), table_name='conversion_factors')
    op.drop_index(op.f('ix_conversion_factors_from_unit'), table_name='conversion_factors')
    op.drop_table('conversion_factors')
    # ### end Alembic commands ###
